eval:
  compute_wer: true
  lm_dir: references/nejm-brain-to-text/language_model/pretrained_language_models/languageModel
  lm_dir_5gram: null
  wer_tag: "5gram"
  wer_every_val_steps: 1
  wer_max_trials: 256
