model:
  decoder_type: reslstm
  reslstm_num_blocks: 1
  reslstm_sublayers_per_block: 2
  reslstm_lstm_layers: 2
  reslstm_lstm_dropout: 0.1
  reslstm_norm: bn
  reslstm_pre_norm: false
  reslstm_residual_dropout: 0.0


gpu_number: "0"

output_dir: trained_models/compare_decoders/reslstm_20k_${now:%Y-%m-%d_%H%M%S}
checkpoint_dir: ${output_dir}/checkpoint

num_training_batches: 20000

dataset:
  num_dataloader_workers: 1

save_all_val_steps: false
save_val_logits: false

wandb:
  enabled: true
  project: brain2text
  run_name: reslstm_20k_${now:%Y-%m-%d_%H%M%S}
  tags: ["compare", "reslstm", "20k"]
